/* Work Station — terminal output simulation data */

window.WS_PROJECTS = [
  {
    id: 'argon',
    name: 'argon-web',
    color: '#7CC4B8',  // teal
    glyph: 'AR',
    branch: 'feat/checkout-redesign',
    sessions: 4,
    cwd: '~/code/argon-web',
    tabs: [
      { id: 't1', label: 'argon-web', cli: 'claude', dirty: true, focused: true,
        layout: { kind: 'split', dir: 'h', ratio: 0.55, a: { kind: 'pane', paneId: 'p1' }, b: { kind: 'split', dir: 'v', ratio: 0.5, a: { kind: 'pane', paneId: 'p2' }, b: { kind: 'pane', paneId: 'p3' } } } },
      { id: 't2', label: 'storybook', cli: 'pnpm', dirty: false,
        layout: { kind: 'pane', paneId: 'p4' } },
      { id: 't3', label: 'logs', cli: 'zsh', dirty: false,
        layout: { kind: 'pane', paneId: 'p5' } },
      { id: 't4', label: 'tests', cli: 'vitest', dirty: true,
        layout: { kind: 'pane', paneId: 'p6' } },
    ],
    panes: {
      p1: { cli: 'claude', cwd: '~/code/argon-web', focused: true, status: 'thinking',
        lines: [
          { t: 'prompt', s: '~/code/argon-web' }, { t: 'cmd', s: 'claude code' },
          { t: 'sys', s: '◆ Claude Code v0.7.2  ·  model: claude-sonnet-4.5' },
          { t: 'sys', s: '  workspace: argon-web  ·  branch: feat/checkout-redesign' },
          { t: 'blank' },
          { t: 'user', s: '> Refactor CheckoutForm to use the new useFormState hook and split address validation into a separate util.' },
          { t: 'blank' },
          { t: 'assistant', s: 'I\'ll refactor this in three steps: extract validators, swap to useFormState, then update tests.' },
          { t: 'blank' },
          { t: 'tool', s: '● Read  src/components/CheckoutForm.tsx  (312 lines)' },
          { t: 'tool', s: '● Read  src/hooks/useFormState.ts  (84 lines)' },
          { t: 'tool', s: '● Grep  validateAddress  in src/' },
          { t: 'dim',  s: '  → 4 matches across 3 files' },
          { t: 'blank' },
          { t: 'tool', s: '● Edit  src/components/CheckoutForm.tsx' },
          { t: 'diff-rm', s: '  - import { useState, useCallback } from \'react\'' },
          { t: 'diff-add', s: '  + import { useFormState } from \'@/hooks/useFormState\'' },
          { t: 'diff-add', s: '  + import { validateAddress } from \'@/lib/validators/address\'' },
          { t: 'blank' },
          { t: 'tool', s: '● Write src/lib/validators/address.ts  (new, 64 lines)' },
          { t: 'ok',   s: '  ✓ created' },
          { t: 'blank' },
          { t: 'thinking', s: '⠋ Updating tests…' },
        ] },
      p2: { cli: 'pnpm', cwd: '~/code/argon-web', status: 'live',
        lines: [
          { t: 'prompt', s: '~/code/argon-web' }, { t: 'cmd', s: 'pnpm dev' },
          { t: 'dim', s: '  ▲ Next.js 14.2.5  ·  turbo' },
          { t: 'info', s: '  - local:   http://localhost:3000' },
          { t: 'info', s: '  - network: http://192.168.1.42:3000' },
          { t: 'blank' },
          { t: 'ok', s: '  ✓ Ready in 1.4s' },
          { t: 'dim', s: '  ✓ Compiled / in 312ms (1142 modules)' },
          { t: 'dim', s: '  ✓ Compiled /checkout in 184ms' },
          { t: 'dim', s: '  GET /  200 in 42ms' },
          { t: 'dim', s: '  GET /checkout  200 in 88ms' },
          { t: 'warn', s: '  ⚠ Fast Refresh had to perform a full reload' },
          { t: 'dim', s: '  ✓ Compiled /checkout in 96ms' },
          { t: 'dim', s: '  GET /checkout  200 in 54ms' },
        ] },
      p3: { cli: 'zsh', cwd: '~/code/argon-web', status: 'idle',
        lines: [
          { t: 'prompt', s: '~/code/argon-web' }, { t: 'cmd', s: 'git status' },
          { t: 'sys', s: 'On branch feat/checkout-redesign' },
          { t: 'sys', s: 'Your branch is ahead of \'origin/feat/checkout-redesign\' by 2 commits.' },
          { t: 'blank' },
          { t: 'sys', s: 'Changes not staged for commit:' },
          { t: 'diff-rm', s: '  modified:   src/components/CheckoutForm.tsx' },
          { t: 'diff-add', s: '  new file:   src/lib/validators/address.ts' },
          { t: 'blank' },
          { t: 'prompt', s: '~/code/argon-web' }, { t: 'cur', s: '' },
        ] },
      p4: { cli: 'pnpm', cwd: '~/code/argon-web', status: 'live',
        lines: [
          { t: 'prompt', s: '~/code/argon-web' }, { t: 'cmd', s: 'pnpm storybook' },
          { t: 'sys', s: '@storybook/cli v8.2.6' },
          { t: 'ok', s: '  ✓ Storybook 8.2 ready in 2.1s' },
          { t: 'info', s: '  → http://localhost:6006' },
        ] },
      p5: { cli: 'zsh', cwd: '~/code/argon-web/logs', status: 'idle',
        lines: [
          { t: 'prompt', s: '~/code/argon-web' }, { t: 'cmd', s: 'tail -f logs/dev.log' },
          { t: 'dim', s: '12:04:11  GET /api/cart  200  18ms' },
          { t: 'dim', s: '12:04:13  GET /api/user 200  9ms' },
        ] },
      p6: { cli: 'vitest', cwd: '~/code/argon-web', status: 'live',
        lines: [
          { t: 'prompt', s: '~/code/argon-web' }, { t: 'cmd', s: 'pnpm test --watch' },
          { t: 'sys', s: 'RUN  v1.6.0  /Users/me/code/argon-web' },
          { t: 'ok', s: '  ✓ src/lib/validators/email.test.ts (8)' },
          { t: 'err', s: '  ✗ src/lib/validators/address.test.ts (3)' },
          { t: 'dim', s: '    → expected "ZIP required" got undefined' },
        ] },
    },
  },
  {
    id: 'pulsar',
    name: 'pulsar-api',
    color: '#E2A85B',
    glyph: 'PU',
    branch: 'main',
    sessions: 2,
    cwd: '~/code/pulsar-api',
    tabs: [
      { id: 'pt1', label: 'pulsar-api', cli: 'kimi', dirty: false, focused: true,
        layout: { kind: 'pane', paneId: 'pp1' } },
      { id: 'pt2', label: 'cargo run', cli: 'cargo', dirty: true,
        layout: { kind: 'pane', paneId: 'pp2' } },
    ],
    panes: {
      pp1: { cli: 'kimi', cwd: '~/code/pulsar-api', focused: true, status: 'idle',
        lines: [
          { t: 'prompt', s: '~/code/pulsar-api' }, { t: 'cmd', s: 'kimi' },
          { t: 'sys', s: '◆ Kimi CLI v0.4.1  ·  k2-chat' },
          { t: 'blank' },
          { t: 'cur', s: '' },
        ] },
      pp2: { cli: 'cargo', cwd: '~/code/pulsar-api', status: 'live',
        lines: [
          { t: 'prompt', s: '~/code/pulsar-api' }, { t: 'cmd', s: 'cargo watch -x run' },
          { t: 'dim', s: '   Compiling pulsar-api v0.3.0' },
          { t: 'ok',  s: '    Finished `dev` profile in 4.21s' },
          { t: 'info', s: '     Running `target/debug/pulsar-api`' },
          { t: 'sys', s: '  pulsar listening on 0.0.0.0:8080' },
        ] },
    },
  },
  {
    id: 'helix',
    name: 'helix-design-system',
    color: '#9D7DD8',
    glyph: 'HX',
    branch: 'release/1.4',
    sessions: 1,
    cwd: '~/code/helix-design-system',
    tabs: [
      { id: 'ht1', label: 'helix', cli: 'codex', dirty: false, focused: true,
        layout: { kind: 'pane', paneId: 'hp1' } },
    ],
    panes: {
      hp1: { cli: 'codex', cwd: '~/code/helix-design-system', focused: true, status: 'idle',
        lines: [
          { t: 'prompt', s: '~/code/helix-design-system' }, { t: 'cmd', s: 'codex' },
          { t: 'sys', s: '◆ codex v1.0.3  ·  gpt-5' },
          { t: 'cur', s: '' },
        ] },
    },
  },
  {
    id: 'orbit',
    name: 'orbit-mobile',
    color: '#E27B7B',
    glyph: 'OR',
    branch: 'feat/auth-v2',
    sessions: 0,
    cwd: '~/code/orbit-mobile',
    tabs: [],
    panes: {},
  },
  {
    id: 'lumen',
    name: 'lumen-marketing',
    color: '#5BA8E2',
    glyph: 'LM',
    branch: 'main',
    sessions: 0,
    cwd: '~/code/lumen-marketing',
    tabs: [],
    panes: {},
  },
  {
    id: 'forge',
    name: 'forge-cli',
    color: '#B5C26E',
    glyph: 'FO',
    branch: 'main',
    sessions: 0,
    cwd: '~/code/forge-cli',
    tabs: [],
    panes: {},
  },
];

window.WS_CLIS = [
  { id: 'claude', name: 'Claude Code', version: '0.7.2',  path: '/usr/local/bin/claude',  badge: 'CC', color: '#C97D5D', desc: 'Anthropic agentic CLI' },
  { id: 'kimi',   name: 'Kimi',        version: '0.4.1',  path: '/usr/local/bin/kimi',    badge: 'KI', color: '#7C9FE2', desc: 'Moonshot k2 chat' },
  { id: 'codex',  name: 'codex',       version: '1.0.3',  path: '/usr/local/bin/codex',   badge: 'CX', color: '#7DC79A', desc: 'OpenAI CLI' },
  { id: 'zsh',    name: 'zsh',         version: '5.9',    path: '/bin/zsh',                badge: 'ZH', color: '#888c93', desc: 'Z shell' },
  { id: 'bash',   name: 'bash',        version: '5.2.21', path: '/bin/bash',               badge: 'BA', color: '#888c93', desc: 'Bourne again shell' },
  { id: 'pwsh',   name: 'PowerShell',  version: '7.4.4',  path: '/usr/local/bin/pwsh',     badge: 'PS', color: '#5C8DC9', desc: 'Cross-platform PowerShell' },
];

window.WS_ICONS = ['AR','PU','HX','OR','LM','FO','NB','SK','TM','VL','XR','ZN'];
window.WS_SWATCHES = ['#7CC4B8','#E2A85B','#9D7DD8','#E27B7B','#5BA8E2','#B5C26E','#D8A0C8','#A0A8B5'];

window.WS_HOTKEYS = [
  { id: 'new-tab',         label: 'New terminal',          binding: ['⌘', 'T'] },
  { id: 'split-v',         label: 'Split vertical',        binding: ['⌘', '\\'] },
  { id: 'split-h',         label: 'Split horizontal',      binding: ['⌘', '⇧', '\\'] },
  { id: 'close-pane',      label: 'Close pane',            binding: ['⌘', 'W'] },
  { id: 'switcher',        label: 'Quick switcher',        binding: ['⌘', 'K'] },
  { id: 'find',            label: 'Find in terminal',      binding: ['⌘', 'F'] },
  { id: 'find-cross',      label: 'Find across sessions',  binding: ['⌘', '⇧', 'F'] },
  { id: 'settings',        label: 'Settings',              binding: ['⌘', ','] },
  { id: 'project-1',       label: 'Switch to project 1',   binding: ['⌘', '1'] },
  { id: 'project-2',       label: 'Switch to project 2',   binding: ['⌘', '2'] },
  { id: 'toggle-sidebar',  label: 'Toggle sidebar',        binding: ['⌘', 'B'] },
  { id: 'new-project',     label: 'New project',           binding: ['⌘', 'N'] },
];

window.WS_SETTINGS = {
  telemetry: false, crashReports: true,
  fallbackCli: 'zsh', scrollbackMb: 4,
  uiFont: 'Geist', monoFont: 'JetBrains Mono',
  uiSize: 13, density: 'comfortable', theme: 'dark', accent: 'teal',
};

window.WS_DEMO_ERRORS = {
  paneSpawnError: { cli: 'claude', message: 'claude: command not found in PATH', cwd: '~/code/argon-web' },
  toastSamples: [
    { type: 'error',   title: 'Failed to save layout', body: 'Database is locked. Try again in a moment.', action: 'Retry' },
    { type: 'warning', title: 'CLI not found',         body: 'Falling back to zsh for new panes.' },
    { type: 'info',    title: 'Update available',      body: 'v0.7.3 is ready.', action: 'Restart' },
    { type: 'success', title: 'Project created',       body: 'lumen-marketing is ready.' },
  ],
};

window.WS_WIN_MENU = [
  { label: 'File', items: [
    { label: 'New project',    keys: ['⌘','N'] },
    { label: 'New terminal',   keys: ['⌘','T'] },
    { label: 'Close pane',     keys: ['⌘','W'] },
    { divider: true },
    { label: 'Settings',       keys: ['⌘',','] },
    { divider: true },
    { label: 'Quit',           keys: ['⌘','Q'] },
  ]},
  { label: 'Edit', items: [
    { label: 'Copy',           keys: ['⌘','C'] },
    { label: 'Paste',          keys: ['⌘','V'] },
    { label: 'Find in pane',   keys: ['⌘','F'] },
  ]},
  { label: 'View', items: [
    { label: 'Toggle sidebar', keys: ['⌘','B'] },
    { label: 'Quick switcher', keys: ['⌘','K'] },
    { label: 'Switch project', keys: ['⌘','1..9'] },
  ]},
  { label: 'Help', items: [
    { label: 'About' },
    { label: 'Documentation' },
    { label: 'Report issue' },
  ]},
];
